### ISSUE TITLE
next champ request

### ISSUE THREAD

**Issue by blesphy1** [AkaneV2/ToxicAio#1]
could you add vlad to toxicaio? been wanting to play him hes super op with scripts haha

**Comment by AkaneV2** [comment]
Done Added Vladimir

**Comment by blesphy1** [comment]
thank you!!!!

**Comment by blesphy1** [comment]
played a few norms with the vlad script you made a fantastic release especially for an initial upload. was wondering if i could hit u up on discord to give feedback for minor changes i think would improve it? hope not to bother u thanks again for ur work

**Comment by AkaneV2** [comment]
> played a few norms with the vlad script you made a fantastic release especially for an initial upload. was wondering if i could hit u up on discord to give feedback for minor changes i think would improve it? hope not to bother u thanks again for ur work

sure you can hit me up Akane#8621 or here on the toxicaio discord https://discord.gg/CQvtqRgvEg
